Atmapplication/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import LoginView, PinView
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^pin/$', PinView.as_view(), name='pin'),
    url(r'^blocked/$', TemplateView.as_view(template_name='blocked.html'), name='blocked'),
    url(r'^interface/', include('atm_interface.urls', namespace='interface')),
    url(r'^error/', TemplateView.as_view(template_name='error.html'), name='error'),
    url(r'^admin/', admin.site.urls),
]

atm_interface/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from atm_interface.views import BalanceView, MoneyView, ExitView, OperationView
from Atmapplication.decorators import pin_required

urlpatterns = [
    url(r'^menu/$', pin_required(TemplateView.as_view(template_name='menu.html')), name='menu'),
    url(r'^balance/$', BalanceView.as_view(), name='balance'),
    url(r'^money/$', MoneyView.as_view(), name='money'),
    url(r'^exit/$', ExitView.as_view(), name='exit'),
    url(r'^operation/$', OperationView.as_view(), name='last_operation'),
    url(r'^notenough/$', TemplateView.as_view(template_name='not_enough.html'), name='not_enough'),
]

atm_interface/models.py
from django.db import models
from django.core.validators import MinLengthValidator

PERSON_SEX_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)


class Person(models.Model):
    """
    Store user data name, age, sex, city
    """

    name = models.CharField(max_length=20, null=False)
    sex = models.CharField(max_length=1, choices=PERSON_SEX_CHOICES)
    age = models.IntegerField()
    city = models.CharField(max_length=20)

    def __str__(self):
        return 'Person {}'.format(self.name)


class Card(models.Model):
    """
    Store card data with number, pin, cvv, cash

    Related to Person model
    """

    number = models.CharField(max_length=16, validators=[MinLengthValidator(16)], null=False)
    pin = models.CharField(max_length=4, validators=[MinLengthValidator(4)], null=False)
    cvv = models.CharField(max_length=3, validators=[MinLengthValidator(3)], null=False)
    blocked = models.BooleanField(default=False)
    cash = models.IntegerField(default=0, null=False)
    person = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return 'Card {}'.format(self.number)

    class Meta:
        ordering = ['cash']


class Operation(models.Model):
    card = models.ForeignKey(Card)
    time = models.TimeField(null=False)
    code = models.IntegerField(null=False)
    cash = models.IntegerField(default=0)

    def __str__(self):
        return 'Operation {} {}'.format(self.id, self.time)

Atmapplication/forms.py
from django import forms
from atm_interface.models import MinLengthValidator


class CardNumberForm(forms.Form):
    number = forms.CharField(max_length=19, validators=[MinLengthValidator(19)],)

Atmapplication/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from Atmapplication.decorators import card_required
from .forms import CardNumberForm
from atm_interface.models import Card


class LoginView(TemplateView):
    """
    User can login by his card number

    When gives right card number - redirected to PinView
    """
    template_name = 'login.html'
    form_class = CardNumberForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            number = ''.join(form.cleaned_data['number'].split('-'))
            try:
                card = Card.objects.get(number=number)
            except Card.DoesNotExist:
                return render(request, self.template_name, {'form': form, 'message': 'Invalid card number'})

            if not card.blocked:
                request.session['card_id'] = card.id
                request.session['incorrect_times'] = 0
                return redirect('/pin')
            return redirect('/blocked')

        return render(request, self.template_name, {'form': form, 'message': 'Invalid card number'})


@method_decorator(card_required, name='get')
class PinView(TemplateView):
    """
    Check pin of the card

    When given right - redirected to the MenuView
    If he gave incorrect pin 4 times - his card will be blocked
    """
    template_name = 'pin.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request):
        card = Card.objects.get(pk=request.session['card_id'])
        request.session['incorrect_times'] += 1

        while request.session['incorrect_times'] < 4:
            if request.POST.get('password') == card.pin:
                request.session['pin_required'] = True
                request.session.pop('incorrect_times')
                request.session.modified = True
                return redirect('/interface/menu/')
            else:
                return render(request, self.template_name, {'message': 'Incorrect pin, please try again'})
        else:
            Card.objects.filter(pk=card.id).update(blocked=True)
            return redirect('/blocked')

atm_interface/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from atm_interface.models import Card, Operation
import datetime
from django.utils.decorators import method_decorator
from Atmapplication.decorators import pin_required


@method_decorator(pin_required, name='get')
class BalanceView(TemplateView):
    """
    Gives information about balance of the card
    """
    template_name = 'balance.html'

    def get(self, request, *args, **kwargs):
        card = Card.objects.get(pk=request.session['card_id'])
        now = datetime.datetime.now()
        Operation.objects.create(card=card,
                                 time=now,
                                 code=1)
        return render(request, self.template_name, {'card': card, 'time': now})


@method_decorator(pin_required, name='get')
class MoneyView(TemplateView):
    """
    Gives user ability to get his money

    if all is ok - redirect to operation
    """
    template_name = 'money.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        card = Card.objects.get(pk=request.session['card_id'])
        if request.POST.get('money') is not None:
            if int(request.POST.get('money')) <= card.cash:
                now = datetime.datetime.now()
                old_val = card.cash
                Card.objects.filter(pk=card.id).update(cash=old_val - int(request.POST.get('money')))
                Operation.objects.create(card=card,
                                         time=now,
                                         code=2,
                                         cash=int(request.POST.get('money')))
                return redirect('/interface/operation')
            return redirect('/interface/notenough')
        return render(request, self.template_name, {'message': 'Please,enter number'})


@method_decorator(pin_required, name='get')
class OperationView(TemplateView):
    """
    Gives information about last operation
    """
    template_name = 'last_operation.html'

    def get(self, request, *args, **kwargs):
        last_operation = Operation.objects.last()
        card = last_operation.card
        return render(request, self.template_name, {'operation': last_operation,
                                                    'card': card})


@method_decorator(pin_required, name='post')
class ExitView(TemplateView):
    """

    """
    template_name = 'login.html'
    def post(self, request):
        request.session.pop('pin_required')
        request.session.pop('card_id')
        return redirect('/')

Atmapplication/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cash machine {% block title %} {% endblock %}</title>
        <link href="{% static 'css/vendor/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" />
    {% block stylecss %}
    {% endblock %}
        <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    {% block javascripts %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}
    <div class="row">
        <div class="container">
            <div class="col-md-4 col-md-offset-4">
    {% block content %}

    {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

Atmapplication/templates/blocked.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <h1>Sorry, your card was blocked</h1>
    <a href="{% url 'login' %}" class="btn btn-default">Back</a>
{% endblock %}

Atmapplication/templates/error.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <h1>Error, you don`t have permissions to do it ...</h1>
    <a href="{% url 'login' %}" class="btn btn-default">Back</a>
{% endblock %}

Atmapplication/templates/keyboard.html
<div class="row button-set">
    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="1"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="2"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="3"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="4"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="5"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="6"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="7"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="8"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="9"/>
    </div>
    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="CLEAR"/>
    </div>

    <div class="form-group col-md-4">
        <input type="button" class="btn btn-default form-control" value="0"/>
    </div>

    <div class="form-group col-md-4">
        <input type="submit" class="btn btn-default form-control" value="OK"/>
    </div>
</div>

Atmapplication/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block javascripts %}
    <script src="{% static 'js/vendor/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}
{% block content %}
        <h1>Card number</h1>
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{  message }}
            <div class="form-group container">
                {{ form.non_fields_errors }}
                <label for="{{ form.number.id_for_label }}"> Enter </label>
                {{ form.number }}
            </div>
            {% include 'keyboard.html' %}
        </form>
{% endblock %}

Atmapplication/templates/pin.html
{% extends "base.html" %}
{% load staticfiles %}
{% block javascripts %}
    <script src="{% static 'js/pin.js' %}"></script>
{% endblock %}
{% block content %}
    <h1>Pin</h1>
    <form action="{% url 'pin' %}" method="post">
        {% csrf_token %}
        {{ message }}
        <div class="form-group">
            <label for="password"> Enter your PIN </label>
            <input id="password" name="password" type="password" class="form-control"/>
        </div>
        {% include 'keyboard.html' %}
    </form>
    <a href="{% url 'login' %}" class="btn btn-default">Back</a>
{% endblock %}

atm_interface/templates/balance.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Balance {% endblock %}
{% block content %}
    <h1>Information</h1>
            <span><strong>Your card number:  </strong></span>{{ card.number }} <br />
            <span><strong>Time:  </strong></span>{{ time }} <br />
            <span><strong>Your cash:  </strong></span>{{ card.cash }}
    {% include 'navigation.html' %}
{% endblock %}

atm_interface/templates/last_operation.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <h1>Thank you</h1>
    <h3>Information about operation</h3>
    <span><strong>Your card number:  </strong></span>{{ card.number }} <br />
    <span><strong>Your withdraw:  </strong></span>{{ operation.cash }} <br />
    <span><strong>Time of operation:  </strong></span>{{ operation.time }} <br />
    <span><strong>Cash on your card:  </strong></span>{{ card.cash }} <br />
    {% include 'navigation.html' %}
{% endblock %}

atm_interface/templates/menu.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Menu {% endblock %}
{% block content %}
    <h1> MENU </h1>
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <a href="{% url 'interface:balance' %}" class="btn btn-default"> Balance </a>
        </div>
        <div class="btn-group" role="group">
            <a href="{% url 'interface:money' %}" class="btn btn-default"> Withdraw money </a>
        </div>
        <div class="btn-group" role="group">
            <form action="{% url 'interface:exit' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Exit" class="btn btn-default"/>
            </form>
        </div>
    </div>
{% endblock %}

atm_interface/templates/money.html
{% extends "base.html" %}
{% load staticfiles %}
{% block javascripts %}
    <script src="{% static 'js/money.js' %}"></script>
{% endblock %}
{% block content %}
    <form action="{% url 'interface:money' %}" method="post">
    {% csrf_token %}
        {{ message }}
        <div class="form-group">
            <label for="money"> Money </label>
            <input id="money" name="money" type="text" class="form-control"/>
        </div>
        {% include 'keyboard.html' %}
    </form>
    {% include 'navigation.html' %}
{% endblock %}

atm_interface/templates/navigation.html
<div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
        <a href="{% url 'interface:menu' %}" class="btn btn-default">Back to menu</a>
    </div>
    <div class="btn-group" role="group">
        <form action="{% url 'interface:exit' %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Exit" class="btn btn-default"/>
        </form>
    </div>
</div>

atm_interface/templates/not_enough.html
{% extends "base.html" %}
{% load staticfiles %}
{% block javascripts %}
    <script src="{% static 'js/money.js' %}"></script>
{% endblock %}
{% block content %}
    <h1>Sorry, not enough money for this operation..</h1>
    {% include 'navigation.html' %}
{% endblock %}